#!/bin/sh

# vim: set ft=sh

# {{@@ header() @@}}
# FILE: ~/.xprofile

# Monitors profiles
{%@@ if profile == VM_HOST @@%}
xrandr --output VGA-1 --primary
{%@@ elif profile == WORK_HOST @@%}
$HOME/.scripts/monitors.zsh
{%@@ endif @@%}

# dpi
xrandr --dpi 96


function xprofile_keyboard() {
  # this is made as a fn because sometimes compose does not work
  # so I can call it again easily

  # Numlock ON
  numlockx

  # Increase key speed via a rate change
  xset r rate 300 50

  # Layouts + compose on ALTGR
  setxkbmap -model pc105 -layout us,it -option compose:ralt
}

xprofile_keyboard


function xprofile_cursor() {
  # for some reason if executed directly does not apply on bspwm
  # so we execute in parallel, waiting 3 seconds

  sleep 3
  # Set cursor in root window (to avoid X in bspwm)
  xsetroot -cursor_name left_ptr
}

xprofile_cursor &

# Set touchpad
LOCAL_TOUCHPAD=$(xinput list | \grep -i touchpad | \grep -o -E 'id=[0-9]+' | cut -d'=' -f2)
if [ ! -z $LOCAL_TOUCHPAD ]; then
  LOCAL_TOUCHPAD_TAP=$(xinput list-props $LOCAL_TOUCHPAD | \grep -i 'tapping enabled' | head -1 | \grep -P -o '\([0-9]+' | tr -d '(')
  xinput set-prop $LOCAL_TOUCHPAD $LOCAL_TOUCHPAD_TAP 1
  LOCAL_TOUCHPAD_NATURAL=$(xinput list-props $LOCAL_TOUCHPAD | \grep -i 'natural scrolling enabled' | head -1 | \grep -P -o '\([0-9]+' | tr -d '(')
  xinput set-prop $LOCAL_TOUCHPAD $LOCAL_TOUCHPAD_NATURAL 1
fi
