# Doc: https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/backgrounds/topos.jpg
}

wallpaper {
  monitor = eDP-1
  path = ~/Pictures/backgrounds/topos.jpg
}

# fallback per qualsiasi altro monitor
# wallpaper {
#   monitor =
#   path = ~/Pictures/backgrounds/topos.jpg
# }

splash = false
