#!/usr/bin/env zsh

DEBUG_FILE=/tmp/dunst_debug

# DUNST_APP_NAME, DUNST_SUMMARY, DUNST_BODY, DUNST_ICON_PATH,
# DUNST_URGENCY, DUNST_ID, DUNST_PROGRESS, DUNST_CATEGORY,
# DUNST_STACK_TAG, DUNST_URLS, DUNST_TIMEOUT, DUNST_TIMESTAMP
# DUNST_STACK_TAG

echo -e "$DUNST_TIMESTAMP\nID: $DUNST_ID\nNAME: $DUNST_APP_NAME\nURGENCY: $DUNST_URGENCY\nSUMMARY: $DUNST_SUMMARY\nBODY: $body\nICON: $DUNST_ICON_PATH\n\n\n" >>$DEBUG_FILE
