#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

$HOME/.config/session-startup.sh

bspc monitor -d code terminal browser 4 5 6 7 8 9 10 im mail music

bspc config border_width 0
bspc config window_gap 3
# based on polybar
# bspc config top_padding 34

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc rule -a Rambox desktop='^11'
bspc rule -a discord desktop='^11'

bspc rule -a Thunderbird desktop='^12'

bspc rule -a Spotify desktop='^13'

bspc rule -a Code desktop='^1'
bspc rule -a code-oss desktop='^1'

bspc rule -a Firefox desktop='^3'
# Remember to right click on chrome titlebar and select `Use system titlebar and borders`
bspc rule -a Chromium desktop='^3'
bspc rule -a Google-chrome desktop='^3'

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
