#!/bin/sh

# interactive events:
#   xev
# list keycode:
#   xmodmap -pke
# determine window class (last string in output):
#   xprop | grep CLASS

# Config =======================================================================

bspc config pointer_modifier mod1

bspc config automatic_scheme alternate
bspc config split_ratio 0.5
bspc config focus_follows_pointer true

# Monitors =====================================================================

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_motion_interval 2

# Desktops =====================================================================

# order: web code term 4 5 6 7 8 9 0 im mail music float
MONITORS=$(xrandr -q | grep -w connected | wc -l)
# Acer Nitro
#MONITOR1=DP-0
#MONITOR2=HDMI-0
# Acer ZenBook
MONITOR1=eDP-1
MONITOR2=HDMI-1-0
if [[ MONITORS -eq 1 ]]; then
  bspc monitor -d float im mail music web code term 4 5 6 7 8 9 10
else
  # front
  bspc monitor $MONITOR2 -d float im web code 5 7 9
  # left
  bspc monitor $MONITOR1 -d mail music term 4 6 8 10
fi

# Windows ======================================================================

# bspc config border_width 2
# bspc config window_gap 4
# bspc config top_padding 34

# without picom is better this way
bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#272822"
bspc config active_border_color "#272822"
bspc config focused_border_color "#474842"
bspc config presel_feedback_color "#01787D"

bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config single_monocle true

# Rules ========================================================================

bspc config external_rules_command "$HOME/.config/bspwm/external-rules"

# bspc rule -a 'class:instance:name'

# Apps with desktop assigned
bspc rule -a Ferdium desktop=im follow=on
bspc rule -a discord desktop=im follow=on
bspc rule -a thunderbird desktop=mail follow=on
bspc rule -a Spotify desktop=music follow=on

# VSCode
bspc rule -a Code desktop=code follow=on
bspc rule -a code-oss desktop=code follow=on

# Firefox (main window and picture-in-picture)
bspc rule -a 'firefox:Navigator:*' desktop=web follow=on
bspc rule -a 'firefox:Toolkit:*' state=floating border=off sticky=on

# Chrome (remember to right click on chrome titlebar and select `Use system titlebar and borders`)
bspc rule -a Chromium desktop=web follow=on
bspc rule -a Google-chrome desktop=web follow=on

# Special floating windows
bspc rule -a linphone state=floating follow=on
bspc rule -a linphone --one-shot hidden=on follow=off
bspc rule -a Simplenote state=floating focus=on follow=on

# Special sticky
bspc rule -a Buttercup state=floating focus=on sticky=on
bspc rule -a Enpass state=floating focus=on sticky=on

# Floating windows
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a Seahorse state=floating focus=on
bspc rule -a Nemo state=floating focus=on
bspc rule -a Gpick state=floating focus=on
bspc rule -a file-roller state=floating focus=on
bspc rule -a pavucontrol state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on

# Autostart ====================================================================

$HOME/.config/autostart.sh
