#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

main() {
  # DEBUG NOTIFICATIONS
  # notify-send "New window" \ "$(echo -e "wid: $wid\nclass: $class\ninstance: $instance\nconsequences: $consequences")"
  notify-send "New window" "class: $class | instance: $instance"

  case "$class" in
  firefox)
    if [ "$instance" = "Toolkit" ]; then
      echo "state=floating sticky=on"
    fi
    ;;
  Spotify)
    echo "desktop=music follow=on"
    ;;
  "")
    sleep 0.5

    wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))

    class=${wm_class[-1]}

    [[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}

    [[ -n "$class" ]] && main
    ;;
  esac
}

main
