#!/bin/sh

# BSPWM External rules =======================================================

# It is called for each new window instance
# and it receives the following arguments
wid=$1
class=$2
instance=$3
consequences=$4

# This script will execute at each new window instance
# ONLY if there is no CLASS name it will loop until it finds one.
# This is needed for some electron applications which set
# their CLASS a while after launch (like Spotify)

main() {
  # DEBUG NOTIFICATIONS:
  # Uncomment one of the following lines to see what BSPWM sees for each new window instance
  # notify-send "New window" "class: $class | instance: $instance"
  # notify-send "New window" \ "$(echo -e "wid: $wid\nclass: $class\ninstance: $instance\nconsequences: $consequences")"

  case "$class" in
  Spotify)
    echo "desktop=music follow=on"
    ;;
  "")
    sleep 0.5

    wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))

    class=${wm_class[-1]}

    [[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}

    [[ -n "$class" ]] && main
    ;;
  esac
}

main
