config:
  backup: true
  create: true
  dotpath: dotfiles
  force_chmod: true
  cmpignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
  instignore:
  - '*/README.md'

# ========================================================================== #
# ========================================================================== #

  minversion: 1.14.0
variables:
  HOME_HOST: FoxPC
  WORK_HOST: FoxDotPc
  VM_HOST: FoxVmArch
  DEFAULT_BROWSER: firefox
  DEFAULT_FILE_MANAGER: nemo
  WM: bspwm
  ROUNDED: 10
  COMPOSITOR: false
  COMPOSITOR_FANCY: false
actions:
  wal: wal -R
  ssh_permissions: find ~/.ssh -type f -name '*' -exec chmod 600 {{}} \;
dotfiles:
  bin:
    src: bin
    dst: ~/.bin
    link: link_children
  scripts:
    src: scripts
    dst: ~/.scripts
  locale:
    src: config/locale.conf
    dst: ~/.config/locale.conf
  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  ssh_simonecingano:
    src: ssh/simonecingano.gpg
    dst: ~/.ssh/simonecingano
    trans_install: gpg
  ssh_simonecingano_pub:
    src: ssh/simonecingano.pub
    dst: ~/.ssh/simonecingano.pub
  ssh_dotvocal:
    src: ssh/dotvocal.gpg
    dst: ~/.ssh/dotvocal
    trans_install: gpg
  ssh_dotvocal_pub:
    src: ssh/dotvocal.pub
    dst: ~/.ssh/dotvocal.pub
  bash_profile:
    src: bash_profile.sh
    dst: ~/.bash_profile
  zshlib:
    src: zsh/zshlib
    dst: ~/.zshlib
    upignore:
    - zplug
    cmpignore:
    - zplug
  zshenv:
    src: zsh/zshenv.zsh
    dst: ~/.zshenv
  zshrc:
    src: zsh/zshrc.zsh
    dst: ~/.zshrc
  nvim:
    src: config/nvim
    dst: ~/.config/nvim
  ruby:
    src: ruby
    dst: ~/
  rubocop:
    src: rubocop.yml
    dst: ~/.rubocop.yml
  pryrc:
    src: pryrc
    dst: ~/.pryrc
  btop:
    src: config/btop
    dst: ~/.config/btop
  bat:
    src: config/bat
    dst: ~/.config/bat
  xprofile:
    src: xprofile
    dst: ~/.xprofile
  xresources:
    src: xresources
    dst: ~/.Xresources
  gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  dconf:
    src: config/dconf
    dst: ~/.config/dconf
  mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  redshift:
    src: config/redshift
    dst: ~/.config/redshift
  alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  kitty:
    src: config/kitty
    dst: ~/.config/kitty
  autostart:
    src: config/autostart.sh
    dst: ~/.config/autostart.sh
  sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  i3:
    src: config/i3
    dst: ~/.config/i3
  bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  picom:
    src: config/picom
    dst: ~/.config/picom
  polybar:
    src: config/polybar
    dst: ~/.config/polybar
  rofi:
    src: config/rofi
    dst: ~/.config/rofi
  wal:
    src: config/wal
    dst: ~/.config/wal
    actions:
    - wal
  dunst:
    src: config/dunst
    dst: ~/.config/dunst
  gsimplecal:
    src: config/gsimplecal
    dst: ~/.config/gsimplecal
  fehbg:
    src: fehbg
    dst: ~/.fehbg
  greenclip:
    src: config/greenclip.toml
    dst: ~/.config/greenclip.toml
  fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  backgrounds:
    src: data/backgrounds
    dst: ~/Pictures/backgrounds
profiles:
  ssh:
    dotfiles:
    - ssh_config
    - ssh_simonecingano
    - ssh_simonecingano_pub
    - ssh_dotvocal
    - ssh_dotvocal_pub
    actions:
    - ssh_permissions

  base_line:
    include:
    - zsh
    - bash
    dotfiles:
    - locale
    - ruby
    - btop
    - nvim
    - bin
    - scripts
    - dir_colors
    - gitconfig
    - bat

  base_gui:
    dotfiles:
    - xprofile
    - xresources
    - gtkrc-2.0
    - gtk-3.0
    - dconf
    - mimeapps.list
    - fontconfig
    - kitty
    - alacritty
    - backgrounds
    - redshift
    - sxhkd
    - autostart

  # Groups ===================================================================

  bash:
    dotfiles:
    - bash_profile

  zsh:
    dotfiles:
    - zshlib
    - zshenv
    - zshrc

  i3:
    dotfiles:
    - i3
    - dunst
    - rofi
    - picom
    - polybar
    - wal
    - gsimplecal
    - fehbg
    - greenclip

  bspwm:
    dotfiles:
    - bspwm
    - dunst
    - rofi
    - picom
    - polybar
    - wal
    - gsimplecal
    - fehbg
    - greenclip

  wsl:
    include:
    - base_line

  # Hosts ====================================================================

  FoxPc:
    include:
    - ssh
    - base_line

  FoxVmArch:
    include:
    - ssh
    - base_line
    - base_gui
    - bspwm
    variables:
      DEFAULT_BROWSER: google-chrome
      COMPOSITOR: false
  FoxDotPc:
    include:
    - ssh
    - base_line
    - base_gui
    - bspwm
    variables:
      DEFAULT_BROWSER: google-chrome
trans_install:
  gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
