# ========================================================================== #
# # DOTDROP Configuration
# see https://github.com/deadc0de6/dotdrop/wiki/
# ========================================================================== #

config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
    - "*/README.md"
  upignore:
    - "*/README.md"
  instignore:
    - "*/README.md"

# ========================================================================== #
# ========================================================================== #

variables:
  # --- Hosts
  HOME_HOST: FoxPC
  WORK_HOST: simodotpc # archfox_work
  VM_HOST: archsimo # archfox_vbox"
  # --- Defaults (adds .desktop to defaults)
  DEFAULT_BROWSER: firefox # firefox, chromium-browser, google-chrome
  DEFAULT_FILE_MANAGER: nemo
  # --- Config (changeable by host)
  WM: bspwm
  ROUNDED: 10
  COMPOSITOR: true
  COMPOSITOR_FANCY: true # blur and opacity

# ========================================================================== #
# ========================================================================== #

actions:
  wal: wal -R
  # need double {{}} to have {} (otherwise arguments substitution)
  ssh_permissions: find ~/.ssh -type f -name '*' -exec chmod 600 {{}} \;

trans_read:
  gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}

# ========================================================================== #
# ========================================================================== #

dotfiles:
  bin:
    src: bin
    dst: ~/.bin
    link: link_children
  scripts:
    src: scripts
    dst: ~/.scripts

  # SSH Keys =================================================================
  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config

  ssh_simonecingano:
    src: ssh/simonecingano.gpg
    dst: ~/.ssh/simonecingano
    trans_read: gpg

  ssh_simonecingano_pub:
    src: ssh/simonecingano.pub
    dst: ~/.ssh/simonecingano.pub

  ssh_dotvocal:
    src: ssh/dotvocal.gpg
    dst: ~/.ssh/dotvocal
    trans_read: gpg

  ssh_dotvocal_pub:
    src: ssh/dotvocal.pub
    dst: ~/.ssh/dotvocal.pub

  # BASH =====================================================================

  bash_profile:
    src: bash_profile.sh
    dst: ~/.bash_profile

  # ZSH ======================================================================
  zshlib:
    src: zsh/zshlib
    dst: ~/.zshlib
    upignore:
      - "zplug"
    cmpignore:
      - "zplug"
  zshenv:
    src: zsh/zshenv.zsh
    dst: ~/.zshenv
  zshrc:
    src: zsh/zshrc.zsh
    dst: ~/.zshrc

  # Programs =================================================================
  nvim:
    src: config/nvim
    dst: ~/.config/nvim
  irbrc:
    src: irbrc
    dst: ~/.irbrc
  pryrc:
    src: pryrc
    dst: ~/.pryrc
  bashtop:
    src: config/bashtop
    dst: ~/.config/bashtop

  # GUI Basics ===============================================================
  xprofile:
    src: xprofile.sh
    dst: ~/.xprofile
  gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  dconf:
    src: config/dconf
    dst: ~/.config/dconf
  mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  redshift:
    src: config/redshift
    dst: ~/.config/redshift

  # Terminals ================================================================
  alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  kitty:
    src: config/kitty
    dst: ~/.config/kitty

  # Environments =============================================================
  autostart:
    src: config/autostart.sh
    dst: ~/.config/autostart.sh
  sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd

  # i3 Environment ===========================================================
  i3:
    src: config/i3
    dst: ~/.config/i3

  # bspwm Environment ========================================================
  bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm

  # i3 / bspwm Environment ===================================================
  picom:
    src: config/picom
    dst: ~/.config/picom
  polybar:
    src: config/polybar
    dst: ~/.config/polybar
  rofi:
    src: config/rofi
    dst: ~/.config/rofi
  wal:
    src: config/wal
    dst: ~/.config/wal
    actions:
      - wal
  dunst:
    src: config/dunst
    dst: ~/.config/dunst
  gsimplecal:
    src: config/gsimplecal
    dst: ~/.config/gsimplecal
  fehbg:
    src: fehbg
    dst: ~/.fehbg
  greenclip:
    src: config/greenclip.toml
    dst: ~/.config/greenclip.toml

  # Others ===================================================================
  fontconfig: # fix for fira code ligatures
    src: config/fontconfig
    dst: ~/.config/fontconfig
  dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  backgrounds:
    src: data/backgrounds
    dst: ~/Pictures/backgrounds

# ========================================================================== #
# ========================================================================== #

profiles:
  # Base =====================================================================

  base_ssh:
    dotfiles:
      - ssh_config
      - ssh_simonecingano
      - ssh_simonecingano_pub
      - ssh_dotvocal
      - ssh_dotvocal_pub
    actions:
      - ssh_permissions

  base_line:
    include:
      - zsh
      - bash
      - base_ssh
    dotfiles:
      - irbrc
      - pryrc
      - nvim
      - bin
      - scripts
      - dir_colors
      - gitconfig

  base_gui:
    dotfiles:
      - xprofile
      - gtkrc-2.0
      - gtk-3.0
      - dconf
      - mimeapps.list
      - fontconfig
      - kitty
      - alacritty
      - backgrounds
      - redshift
      - sxhkd
      - autostart

  # Groups ===================================================================

  bash:
    dotfiles:
      - bash_profile

  zsh:
    dotfiles:
      - zshlib
      - zshenv
      - zshrc

  i3:
    dotfiles:
      - i3
      - dunst
      - rofi
      - picom
      - polybar
      - wal
      - gsimplecal
      - fehbg
      - greenclip

  bspwm:
    dotfiles:
      - bspwm
      - dunst
      - rofi
      - picom
      - polybar
      - wal
      - gsimplecal
      - fehbg
      - greenclip

  wsl:
    include:
      - base_line

  # Hosts ====================================================================

  FoxPC: # Home (windows)
    include:
      - base_line

  archsimo: # Work (Virtualbox)
    include:
      - base_line
      - base_gui
      - i3
      - bspwm
    variables:
      DEFAULT_BROWSER: google-chrome
      COMPOSITOR: false

  simodotpc: # Work (Office)
    include:
      - base_line
      - base_gui
      - i3
      - bspwm
    variables:
      DEFAULT_BROWSER: google-chrome
