# {{@@ header() @@}}
# FILE: ~/.rubocop.yml

AllCops:
  Exclude:
    - "docs"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/GuardClause:
  Enabled: false
