# {{@@ header() @@}}
# FILE: ~/.rubocop.yml

AllCops:
  Exclude:
    - "docs"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 3.0
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
