
# Centra qualsiasi finestra che nasce floating
# windowrulev2 = center, floating:1 # questo e' stupido, i menu vanno a puttane

# Dialog
windowrule {
  name = windowrule-1
  float = on
  center = on
  match:title = ^(Save |Open ).*
}


# Workspace
windowrule {
  name = windowrule-2
  workspace = name:!1:im
  match:class = ^(Ferdium|ferdium)$
}

windowrule {
  name = windowrule-3
  workspace = name:!1:im
  match:class = ^(Discord|discord)$
}

windowrule {
  name = windowrule-4
  workspace = name:!2:mail
  match:class = ^(Thunderbird|thunderbird)$
}

windowrule {
  name = windowrule-5
  workspace = name:!3:music
  match:class = ^(Spotify|spotify)$
}

windowrule {
  name = windowrule-6
  workspace = name:02:code
  match:class = ^(Code|code|code-oss)$
}


# Web (Firefox + Chromium/Chrome)
windowrule {
  name = windowrule-7
  workspace = name:01:web
  match:class = ^(firefox)$
}

windowrule {
  name = windowrule-8
  workspace = name:01:web
  match:class = ^(Chromium|chromium|Google-chrome|google-chrome)$
}


# Firefox normale
# Hack per firefox
windowrule {
  name = windowrule-9
  float = on
  border_size = 0
  center = on
  stay_focused = on
  match:class = ^(firefox)$
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = windowrule-10
  float = on
  border_size = 0
  center = on
  match:class = ^(firefox)$
  match:title = ^(.*Toolkit.*)$
}


# Float, center e pin
windowrule {
  name = windowrule-11
  float = on
  pin = on
  center = on
  match:class = ^(Enpass|enpass)$
}


# Float, center
windowrule {
  name = windowrule-12
  float = on
  center = on
  match:class = ^(Simplenote|simplenote)$
}

windowrule {
  name = windowrule-13
  float = on
  center = on
  match:class = ^(Pavucontrol|pavucontrol|org.pulseaudio.pavucontrol)$
}

windowrule {
  name = windowrule-14
  float = on
  center = on
  match:class = ^(Seahorse|seahorse)$
}

windowrule {
  name = windowrule-15
  float = on
  center = on
  match:class = ^(Nemo|nemo)$
}

windowrule {
  name = windowrule-16
  float = on
  center = on
  match:class = ^(Gpick|gpick)$
}

windowrule {
  name = windowrule-17
  float = on
  center = on
  match:class = ^(file-roller)$
}

windowrule {
  name = windowrule-18
  float = on
  center = on
  match:class = ^(Lxappearance|lxappearance)$
}
